### ISSUE TITLE
Got a warning during the Diagnostics step

### ISSUE THREAD

**Issue by Kamaradeivanov** [jaxxstorm/pulumi-scaleway#5]
When I do a pulumi up I got the following warning 

`[WARN] cannot load configuration: scaleway-sdk-go: cannot read config file /home/ivanov/.config/scw/config.yaml: no such file or directory`

**Comment by jaxxstorm** [comment]
This error is propagated through from the scaleway sdk.

It can be fixed by creating an empty file:

```
mkdir -p /home/ivanov/.config/scw/
touch  /home/ivanov/.config/scw/config.yaml
```
